[package]
name = "rwelcome"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0"
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.192", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
